/**
 * The `iosA` draft: iOS pass A, the web's layout on iOS - the setup sentence,
 * Settings, Help and the (i) - which shares the web's keys and retires the
 * iOS ones they replace, on `91d5fff`. Three new keys, all iOS's: the (i)'s
 * expanded and collapsed, and the units' (i) with "phone" for "browser".
 *
 * What a draft is, and how the proofs read it: ../copyDraft.ts.
 */

import type { Draft, Drafted } from '../copyDraft.js';

/** iOS pass A (UI.md, "As built (iOS, pass A)"): no wording changes but
 *  three new iOS keys; the rest is which app says what. */
const IOS_A_DRAFT: Drafted[] = [
  {
    key: 'readout.phase.totalLidOn', row: "retired on iOS",
    before: { text: "Total time, lid on" },
    after: null,
    appsBefore: ["ios"], appsAfter: [],
  },
  {
    key: 'readout.sub.coldAssumes', row: "shared with iOS",
    before: { text: "about {boil} to boil, based on history" },
    after: { text: "about {boil} to boil, based on history" },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'readout.sub.coldAssumes.info', row: "shared with iOS",
    before: { text: "About this boil time" },
    after: { text: "About this boil time" },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'readout.sub.coldAssumes.more', row: "shared with iOS",
    before: { text: "Each time you tap Full rolling boil on a cold-water start, I note how long the water took, and blend it half and half with what I had for that much water. I can't tell your pots apart, only how much water is in them. If I've never timed this much, I scale from the nearest amount I have. Tap the boil today and I'll correct the time while the eggs cook." },
    after: { text: "Each time you tap Full rolling boil on a cold-water start, I note how long the water took, and blend it half and half with what I had for that much water. I can't tell your pots apart, only how much water is in them. If I've never timed this much, I scale from the nearest amount I have. Tap the boil today and I'll correct the time while the eggs cook." },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'readout.sub.coldGuesses', row: "shared with iOS",
    before: { text: "I'm guessing {boil} to boil — tap when it does" },
    after: { text: "I'm guessing {boil} to boil — tap when it does" },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'readout.sub.standing', row: "shared with iOS",
    before: { text: "for this much water with the lid on ({water}) — measure the water, it changes the time" },
    after: { text: "for this much water with the lid on ({water}) — measure the water, it changes the time" },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'readout.sub.hot', row: "shared with iOS",
    before: { text: "from eggs in to eggs out" },
    after: { text: "from eggs in to eggs out" },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'readout.sub.idleCold', row: "retired on iOS",
    before: { text: "from eggs into cold water, heat on, to eggs out" },
    after: null,
    appsBefore: ["ios"], appsAfter: [],
  },
  {
    key: 'readout.sub.idleHot', row: "retired on iOS",
    before: { text: "from eggs into boiling water to eggs out" },
    after: null,
    appsBefore: ["ios"], appsAfter: [],
  },
  {
    key: 'readout.stat.peakYolk', row: "retired on iOS",
    before: { text: "peak yolk" },
    after: null,
    appsBefore: ["ios"], appsAfter: [],
  },
  {
    key: 'readout.stat.peakWhite', row: "retired on iOS",
    before: { text: "peak white" },
    after: null,
    appsBefore: ["ios"], appsAfter: [],
  },
  {
    key: 'readout.stat.afterBoil', row: "retired on iOS",
    before: { text: "after the boil" },
    after: null,
    appsBefore: ["ios"], appsAfter: [],
  },
  {
    key: 'readout.stat.waterBoilsAt', row: "shared with iOS",
    before: { text: "water boils at" },
    after: { text: "water boils at" },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'readout.stat.bath', row: "retired on iOS",
    before: { text: "sous-vide at" },
    after: null,
    appsBefore: ["ios"], appsAfter: [],
  },
  {
    key: 'action.startHeating', row: "shared with iOS",
    before: { text: "Start heating" },
    after: { text: "Start heating" },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'action.eggsInHeatOn', row: "retired on iOS",
    before: { text: "Eggs in, heat on" },
    after: null,
    appsBefore: ["ios"], appsAfter: [],
  },
  {
    key: 'action.hint.cold', row: "shared with iOS",
    before: { text: "eggs in the pan, lid on, then tap" },
    after: { text: "eggs in the pan, lid on, then tap" },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'action.hint.hotStanding', row: "shared with iOS",
    before: { text: "eggs into boiling water, then lid on and heat off" },
    after: { text: "eggs into boiling water, then lid on and heat off" },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'action.hint.hotBoiling', row: "shared with iOS",
    before: { text: "water at a full rolling boil, and kept there for the whole {time}" },
    after: { text: "water at a full rolling boil, and kept there for the whole {time}" },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'action.hint.whiteNeverSets', row: "shared with iOS",
    before: { text: "nothing to start: with this much water the white never sets" },
    after: { text: "nothing to start: with this much water the white never sets" },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'action.hint.heating', row: "shared with iOS",
    before: { text: "wait for the whole surface to roll" },
    after: { text: "wait for the whole surface to roll" },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'action.hint.heating.info', row: "shared with iOS",
    before: { text: "About the rolling boil" },
    after: { text: "About the rolling boil" },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'action.hint.heating.more', row: "shared with iOS",
    before: { text: "A full rolling boil is when the whole surface is heaving and stirring doesn't calm it, not the first bubbles at the edge. The rest of the cook is timed from your tap, and it teaches me how fast your stove boils water, so a few seconds either way is fine, but a minute early isn't. Until you tap, the countdown is my guess." },
    after: { text: "A full rolling boil is when the whole surface is heaving and stirring doesn't calm it, not the first bubbles at the edge. The rest of the cook is timed from your tap, and it teaches me how fast your stove boils water, so a few seconds either way is fine, but a minute early isn't. Until you tap, the countdown is my guess." },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'action.hint.heatingStanding', row: "shared with iOS",
    before: { text: "wait for the whole surface to roll, then lid on and heat off" },
    after: { text: "wait for the whole surface to roll, then lid on and heat off" },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'controls.doneness.value', row: "shared with iOS",
    before: { text: "{doneness} · peak yolk {yolk}" },
    after: { text: "{doneness} · peak yolk {yolk}" },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'controls.size', row: "shared with iOS",
    before: { text: "Egg size" },
    after: { text: "Egg size" },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'controls.egg.more', row: "shared with iOS",
    before: { text: "The heat has to reach the middle of the egg, and a bigger egg's middle is further from the water. A size from the box covers eggs of quite different weights, so if you have kitchen scales, weigh one and type the weight in, and I'll use that instead of the box." },
    after: { text: "The heat has to reach the middle of the egg, and a bigger egg's middle is further from the water. A size from the box covers eggs of quite different weights, so if you have kitchen scales, weigh one and type the weight in, and I'll use that instead of the box." },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'controls.measure.weight', row: "shared with iOS",
    before: { text: "Weight" },
    after: { text: "Weight" },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'controls.eggFrom.more', row: "shared with iOS",
    before: { text: "A fridge keeps its eggs at much the same temperature every day, so I know where a fridge egg starts. A room can be a few degrees warmer or cooler than I assume, and every degree moves the time a little. If you know better, pick Custom and tell me. An egg that has been sitting out is at room temperature, so it also tells me how warm your kitchen is, which matters when the eggs rest on the counter or the heat goes off." },
    after: { text: "A fridge keeps its eggs at much the same temperature every day, so I know where a fridge egg starts. A room can be a few degrees warmer or cooler than I assume, and every degree moves the time a little. If you know better, pick Custom and tell me. An egg that has been sitting out is at room temperature, so it also tells me how warm your kitchen is, which matters when the eggs rest on the counter or the heat goes off." },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'controls.eggFrom.fridge', row: "shared with iOS",
    before: { text: "Fridge" },
    after: { text: "Fridge" },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'controls.eggFrom.room', row: "shared with iOS",
    before: { text: "Room" },
    after: { text: "Room" },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'controls.eggFrom.custom', row: "shared with iOS",
    before: { text: "Custom" },
    after: { text: "Custom" },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'controls.eggFrom.fridgeAt', row: "retired on iOS",
    before: { text: "Fridge {temp}" },
    after: null,
    appsBefore: ["ios"], appsAfter: [],
  },
  {
    key: 'controls.eggFrom.roomAt', row: "retired on iOS",
    before: { text: "Room {temp}" },
    after: null,
    appsBefore: ["ios"], appsAfter: [],
  },
  {
    key: 'controls.eggFrom.hint', row: "shared with iOS",
    before: { text: "Assumed temperatures — fridge: {fridge}, room: {room}. Pick Custom if yours differ." },
    after: { text: "Assumed temperatures — fridge: {fridge}, room: {room}. Pick Custom if yours differ." },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'controls.eggTemp', row: "shared with iOS",
    before: { text: "Egg temperature" },
    after: { text: "Egg temperature" },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'controls.start.more', row: "shared with iOS",
    before: { text: "Boiling water: lower the eggs into water that's already at a full boil, and the clock starts as they go in. They peel more easily. Cold water: eggs in a cold pan, heat on, and you tap when it boils, which teaches me how fast your stove boils water. They're done sooner, counting the wait for the boil. Sous-vide: I'll tell you when you should have started. It's usually a while ago." },
    after: { text: "Boiling water: lower the eggs into water that's already at a full boil, and the clock starts as they go in. They peel more easily. Cold water: eggs in a cold pan, heat on, and you tap when it boils, which teaches me how fast your stove boils water. They're done sooner, counting the wait for the boil. Sous-vide: I'll tell you when you should have started. It's usually a while ago." },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'controls.start.hintSousVide', row: "retired on iOS",
    before: { text: "A bath needs no pan, so the pan controls are put away. Your settings are kept and come back when you pick a pan again." },
    after: null,
    appsBefore: ["ios"], appsAfter: [],
  },
  {
    key: 'controls.afterTheBoil.more', row: "shared with iOS",
    before: { text: "Keep boiling: the burner holds the water at a full boil until the eggs come out, and how much water there is hardly matters. Heat off, lid on: once the eggs are in boiling water, turn the burner off, put the lid on, and the hot water finishes the eggs as it cools. That saves energy, but the water is doing all the work, so how much there is decides the time, and with too little it can't finish the job. Measure it if you choose this." },
    after: { text: "Keep boiling: the burner holds the water at a full boil until the eggs come out, and how much water there is hardly matters. Heat off, lid on: once the eggs are in boiling water, turn the burner off, put the lid on, and the hot water finishes the eggs as it cools. That saves energy, but the water is doing all the work, so how much there is decides the time, and with too little it can't finish the job. Measure it if you choose this." },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'controls.afterBoil.explainHeatOff', row: "retired on iOS",
    before: { text: "Lid on and burner off: the water's own heat finishes the eggs. I work out the time from the water below, so measure it — more or less water changes the time, or whether it works at all." },
    after: null,
    appsBefore: ["ios"], appsAfter: [],
  },
  {
    key: 'controls.afterBoil.explainHold', row: "retired on iOS",
    before: { text: "The burner holds the water at a rolling boil for the whole cook." },
    after: null,
    appsBefore: ["ios"], appsAfter: [],
  },
  {
    key: 'controls.then', row: "retired on iOS",
    before: { text: "Then" },
    after: null,
    appsBefore: ["ios"], appsAfter: [],
  },
  {
    key: 'controls.cooling', row: "shared with iOS",
    before: { text: "Cooling" },
    after: { text: "Cooling" },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'controls.cooling.more', row: "shared with iOS",
    before: { text: "When the eggs come out, the heat in the white keeps moving inward, and the yolk goes on cooking for a few minutes. Ice water takes the heat away fastest, so it stops that soonest and lets me offer the softest yolks; a cold tap is nearly as good. Still air barely takes heat away at all: to a hot egg on the counter it is less a way of cooling than a lid. I allow for that, but it rules out the softest yolks, and how much more the yolk cooks is hard to predict." },
    after: { text: "When the eggs come out, the heat in the white keeps moving inward, and the yolk goes on cooking for a few minutes. Ice water takes the heat away fastest, so it stops that soonest and lets me offer the softest yolks; a cold tap is nearly as good. Still air barely takes heat away at all: to a hot egg on the counter it is less a way of cooling than a lid. I allow for that, but it rules out the softest yolks, and how much more the yolk cooks is hard to predict." },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'controls.water.more', row: "shared with iOS",
    before: { text: "How much water goes in the pan, not counting the eggs. It matters most with the heat off, when the water's own heat does the cooking: more water holds its heat longer. It matters a little with the heat on, because cold eggs going into boiling water cool a little water more than a lot. And I remember how long it takes to boil each amount you use, so it's worth measuring." },
    after: { text: "How much water goes in the pan, not counting the eggs. It matters most with the heat off, when the water's own heat does the cooking: more water holds its heat longer. It matters a little with the heat on, because cold eggs going into boiling water cool a little water more than a lot. And I remember how long it takes to boil each amount you use, so it's worth measuring." },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'controls.eggsInPan.more', row: "shared with iOS",
    before: { text: "How many eggs go in together. Cold eggs take heat out of boiling water as they go in, and more eggs take more, so the water takes longer to recover, or with the heat off never does. For eggs that start in cold water it makes no difference to my sums: you tap when the water boils, and that already counts them." },
    after: { text: "How many eggs go in together. Cold eggs take heat out of boiling water as they go in, and more eggs take more, so the water takes longer to recover, or with the heat off never does. For eggs that start in cold water it makes no difference to my sums: you tap when the water boils, and that already counts them." },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'controls.altitude.more', row: "shared with iOS",
    before: { text: "Higher up, the air presses down less, so water boils cooler, and cooler water cooks more slowly. It adds up: a kitchen up a mountain needs noticeably longer than one by the sea. Tell me roughly how high you are, and I'll cook at the boiling point shown here." },
    after: { text: "Higher up, the air presses down less, so water boils cooler, and cooler water cooks more slowly. It adds up: a kitchen up a mountain needs noticeably longer than one by the sea. Tell me roughly how high you are, and I'll cook at the boiling point shown here." },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'help.link', row: "shared with iOS",
    before: { text: "Help" },
    after: { text: "Help" },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'help.title', row: "shared with iOS",
    before: { text: "Help" },
    after: { text: "Help" },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'help.how.title', row: "shared with iOS",
    before: { text: "How I work" },
    after: { text: "How I work" },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'help.how.p1', row: "shared with iOS",
    before: { text: "I don't use a rule of thumb. I work out how heat soaks into your egg from the water, and how far the yolk and the white set on the way, then pick the time that stops the yolk where you asked." },
    after: { text: "I don't use a rule of thumb. I work out how heat soaks into your egg from the water, and how far the yolk and the white set on the way, then pick the time that stops the yolk where you asked." },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'help.how.aside', row: "shared with iOS",
    before: { text: "Technically: [heat conduction](https://en.wikipedia.org/wiki/Heat_equation) through a sphere the size of your egg, and protein setting as a dose of heat over time, from the [Arrhenius equation](https://en.wikipedia.org/wiki/Arrhenius_equation). Every constant, with its source, is in the [README](https://github.com/danmackinlay/actual_egg_timer#2-the-physical-model)." },
    after: { text: "Technically: [heat conduction](https://en.wikipedia.org/wiki/Heat_equation) through a sphere the size of your egg, and protein setting as a dose of heat over time, from the [Arrhenius equation](https://en.wikipedia.org/wiki/Arrhenius_equation). Every constant, with its source, is in the [README](https://github.com/danmackinlay/actual_egg_timer#2-the-physical-model)." },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'help.how.p2', row: "shared with iOS",
    before: { text: "The cooling counts too. An egg out of the water keeps cooking from the inside for a few minutes. Ice water stops that soonest; the counter barely slows it." },
    after: { text: "The cooling counts too. An egg out of the water keeps cooking from the inside for a few minutes. Ice water stops that soonest; the counter barely slows it." },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'help.how.aside2', row: "shared with iOS",
    before: { text: "On the counter, still air takes heat out so slowly that the yolk ends up within a fraction of a degree of where it would if the egg never cooled at all. [README §5](https://github.com/danmackinlay/actual_egg_timer#5-carryover-the-cooling-step-is-part-of-the-recipe)." },
    after: { text: "On the counter, still air takes heat out so slowly that the yolk ends up within a fraction of a degree of where it would if the egg never cooled at all. [README §5](https://github.com/danmackinlay/actual_egg_timer#5-carryover-the-cooling-step-is-part-of-the-recipe)." },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'help.learn.title', row: "shared with iOS",
    before: { text: "What I learn, and from what" },
    after: { text: "What I learn, and from what" },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'help.learn.p1', row: "shared with iOS",
    before: { text: "Your answers teach me three things: how you like your yolk, how your eggs' whites behave, and how fast your stove boils water. A probe reading teaches me how fast heat gets into your eggs, all at once. Every question is optional." },
    after: { text: "Your answers teach me three things: how you like your yolk, how your eggs' whites behave, and how fast your stove boils water. A probe reading teaches me how fast heat gets into your eggs, all at once. Every question is optional." },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'help.learn.aside', row: "shared with iOS",
    before: { text: "I keep a cloud of guesses about your eggs and your taste, and each answer reweights them: [sequential Monte Carlo](https://en.wikipedia.org/wiki/Particle_filter), with an [ordered probit](https://en.wikipedia.org/wiki/Ordered_probit) for too soft, just right or too firm. I keep every egg, so when I improve, I relearn from all of them. [The design](https://github.com/danmackinlay/actual_egg_timer/blob/main/INFERENCE.md)." },
    after: { text: "I keep a cloud of guesses about your eggs and your taste, and each answer reweights them: [sequential Monte Carlo](https://en.wikipedia.org/wiki/Particle_filter), with an [ordered probit](https://en.wikipedia.org/wiki/Ordered_probit) for too soft, just right or too firm. I keep every egg, so when I improve, I relearn from all of them. [The design](https://github.com/danmackinlay/actual_egg_timer/blob/main/INFERENCE.md)." },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'help.reliable.title', row: "shared with iOS",
    before: { text: "Getting reliable eggs" },
    after: { text: "Getting reliable eggs" },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'help.reliable.intro', row: "shared with iOS",
    before: { text: "The biggest help is telling me how each egg came out. After that, it depends on how you cook." },
    after: { text: "The biggest help is telling me how each egg came out. After that, it depends on how you cook." },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'help.reliable.forYou', row: "shared with iOS",
    before: { text: "For the eggs you've set up now" },
    after: { text: "For the eggs you've set up now" },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'help.reliable.every.title', row: "shared with iOS",
    before: { text: "Whichever way you cook" },
    after: { text: "Whichever way you cook" },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'help.reliable.every', row: "shared with iOS",
    before: { text: "Weigh the egg if you can: one size on the box covers eggs that need quite different times. Eggs straight from the fridge are more predictable than eggs at room temperature." },
    after: { text: "Weigh the egg if you can: one size on the box covers eggs that need quite different times. Eggs straight from the fridge are more predictable than eggs at room temperature." },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'help.reliable.hot.title', row: "shared with iOS",
    before: { text: "Into boiling water" },
    after: { text: "Into boiling water" },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'help.reliable.hot', row: "shared with iOS",
    before: { text: "The easiest to get right. Keep the water at a full rolling boil the whole time." },
    after: { text: "The easiest to get right. Keep the water at a full rolling boil the whole time." },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'help.reliable.cold.title', row: "shared with iOS",
    before: { text: "Into cold water" },
    after: { text: "Into cold water" },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'help.reliable.cold', row: "shared with iOS",
    before: { text: "Tap Full rolling boil when the whole surface rolls, not at the first bubbles. That tap corrects my time while the eggs cook." },
    after: { text: "Tap Full rolling boil when the whole surface rolls, not at the first bubbles. That tap corrects my time while the eggs cook." },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'help.reliable.heatOff.title', row: "shared with iOS",
    before: { text: "Heat off, lid on" },
    after: { text: "Heat off, lid on" },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'help.reliable.heatOff', row: "shared with iOS",
    before: { text: "The water does all the cooking, so measure it, and use plenty. With too little, the white never sets." },
    after: { text: "The water does all the cooking, so measure it, and use plenty. With too little, the white never sets." },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'help.reliable.cooling.title', row: "shared with iOS",
    before: { text: "Ice, tap or counter" },
    after: { text: "Ice, tap or counter" },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'help.reliable.cooling', row: "shared with iOS",
    before: { text: "Ice water is the most predictable, a cold tap is nearly as good, and the counter keeps cooking the yolk. For soft eggs, use ice." },
    after: { text: "Ice water is the most predictable, a cold tap is nearly as good, and the counter keeps cooking the yolk. For soft eggs, use ice." },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'help.odds.title', row: "shared with iOS",
    before: { text: "How sure I am" },
    after: { text: "How sure I am" },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'help.odds.p1', row: "shared with iOS",
    before: { text: "I tell you which way an egg is likely to miss, and the bracket under the slider shows how firm the yolk will probably be. Both narrow as I learn." },
    after: { text: "I tell you which way an egg is likely to miss, and the bracket under the slider shows how firm the yolk will probably be. Both narrow as I learn." },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'help.odds.aside', row: "shared with iOS",
    before: { text: "The bracket covers eight eggs in ten. When I choose the time, a runny white counts three times as bad as a yolk a little too firm, so I lean slightly long. The slider's shading shows how often each doneness comes out right for you." },
    after: { text: "The bracket covers eight eggs in ten. When I choose the time, a runny white counts three times as bad as a yolk a little too firm, so I lean slightly long. The slider's shading shows how often each doneness comes out right for you." },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'help.unsure.title', row: "shared with iOS",
    before: { text: "Where I'm unsure" },
    after: { text: "Where I'm unsure" },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'help.unsure.counter', row: "shared with iOS",
    before: { text: "The counter. Nobody seems to have published how fast an egg cools in still air, so that is my weakest number." },
    after: { text: "The counter. Nobody seems to have published how fast an egg cools in still air, so that is my weakest number." },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'help.unsure.heatOff', row: "shared with iOS",
    before: { text: "Heat off. I assume an ordinary pan with its lid on; a heavy pot or a loose lid will change the time." },
    after: { text: "Heat off. I assume an ordinary pan with its lid on; a heavy pot or a loose lid will change the time." },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'help.unsure.white', row: "shared with iOS",
    before: { text: "Whites. I can't tell a white that sets late from a cook who calls a tender white runny." },
    after: { text: "Whites. I can't tell a white that sets late from a cook who calls a tender white runny." },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'help.unsure.sousVide', row: "shared with iOS",
    before: { text: "Sous-vide. Below {floor} the white stays liquid and moves inside the shell, which I leave out, so I'm not reliable there. The very long times are real, though: that cool, the white takes most of a day to set." },
    after: { text: "Sous-vide. Below {floor} the white stays liquid and moves inside the shell, which I leave out, so I'm not reliable there. The very long times are real, though: that cool, the white takes most of a day to set." },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'help.sources.title', row: "shared with iOS",
    before: { text: "Sources" },
    after: { text: "Sources" },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'help.sources.intro', row: "shared with iOS",
    before: { text: "The main sources behind my numbers. The [README](https://github.com/danmackinlay/actual_egg_timer#10-references) lists them all, with what each one settled." },
    after: { text: "The main sources behind my numbers. The [README](https://github.com/danmackinlay/actual_egg_timer#10-references) lists them all, with what each one settled." },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'help.source.williams', row: "shared with iOS",
    before: { text: "C. D. H. Williams, \"The Science of Boiling an Egg\", University of Exeter (1998). newton.ex.ac.uk/teaching/CDHW/egg (the host is gone; the page is in the Internet Archive)" },
    after: { text: "C. D. H. Williams, \"The Science of Boiling an Egg\", University of Exeter (1998). newton.ex.ac.uk/teaching/CDHW/egg (the host is gone; the page is in the Internet Archive)" },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'help.source.buay', row: "shared with iOS",
    before: { text: "D. Buay, S. K. Foong, D. Kiang, L. Kuppan and V. H. Liew, \"How long does it take to boil an egg? Revisited\", European Journal of Physics 27, 119-131 (2006). doi:10.1088/0143-0807/27/1/013" },
    after: { text: "D. Buay, S. K. Foong, D. Kiang, L. Kuppan and V. H. Liew, \"How long does it take to boil an egg? Revisited\", European Journal of Physics 27, 119-131 (2006). doi:10.1088/0143-0807/27/1/013" },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'help.source.abbasnezhad', row: "shared with iOS",
    before: { text: "B. Abbasnezhad, N. Hamdami, J.-Y. Monteau and H. Vatankhah, \"Numerical modeling of heat transfer and pasteurizing value during thermal processing of intact egg\", Food Science & Nutrition 4, 42-49 (2016). doi:10.1002/fsn3.257" },
    after: { text: "B. Abbasnezhad, N. Hamdami, J.-Y. Monteau and H. Vatankhah, \"Numerical modeling of heat transfer and pasteurizing value during thermal processing of intact egg\", Food Science & Nutrition 4, 42-49 (2016). doi:10.1002/fsn3.257" },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'help.source.denys', row: "shared with iOS",
    before: { text: "S. Denys, J. G. Pieters and K. Dewettinck, \"Computational fluid dynamics analysis of combined conductive and convective heat transfer in model eggs\", Journal of Food Engineering 63, 281-290 (2004). doi:10.1016/j.jfoodeng.2003.06.002" },
    after: { text: "S. Denys, J. G. Pieters and K. Dewettinck, \"Computational fluid dynamics analysis of combined conductive and convective heat transfer in model eggs\", Journal of Food Engineering 63, 281-290 (2004). doi:10.1016/j.jfoodeng.2003.06.002" },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'help.source.vega', row: "shared with iOS",
    before: { text: "C. Vega and R. Mercadé-Prieto, \"Culinary Biophysics: on the Nature of the 6X °C Egg\", Food Biophysics 6, 152-159 (2011). doi:10.1007/s11483-010-9200-1" },
    after: { text: "C. Vega and R. Mercadé-Prieto, \"Culinary Biophysics: on the Nature of the 6X °C Egg\", Food Biophysics 6, 152-159 (2011). doi:10.1007/s11483-010-9200-1" },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'help.source.weijers', row: "shared with iOS",
    before: { text: "M. Weijers, P. A. Barneveld, M. A. Cohen Stuart and R. W. Visschers, \"Heat-induced denaturation and aggregation of ovalbumin at neutral pH described by irreversible first-order kinetics\", Protein Science 12, 2693-2703 (2003). doi:10.1110/ps.03242803" },
    after: { text: "M. Weijers, P. A. Barneveld, M. A. Cohen Stuart and R. W. Visschers, \"Heat-induced denaturation and aggregation of ovalbumin at neutral pH described by irreversible first-order kinetics\", Protein Science 12, 2693-2703 (2003). doi:10.1110/ps.03242803" },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'help.source.hoyt', row: "shared with iOS",
    before: { text: "D. F. Hoyt, \"Practical methods of estimating volume and fresh weight of bird eggs\", The Auk 96, 73-77 (1979)." },
    after: { text: "D. F. Hoyt, \"Practical methods of estimating volume and fresh weight of bird eggs\", The Auk 96, 73-77 (1979)." },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'help.source.usda', row: "shared with iOS",
    before: { text: "USDA Food Safety and Inspection Service, \"High Altitude Cooking\"." },
    after: { text: "USDA Food Safety and Inspection Service, \"High Altitude Cooking\"." },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'learned.title', row: "shared with iOS",
    before: { text: "What I've learned" },
    after: { text: "What I've learned" },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'more.about', row: "shared with iOS",
    before: { text: "About {label}" },
    after: { text: "About {label}" },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'setup.sentence', row: "shared with iOS",
    before: { text: "{egg} {from}, {start}, {cooling}." },
    after: { text: "{egg} {from}, {start}, {cooling}." },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'setup.sentenceSousVide', row: "shared with iOS",
    before: { text: "{egg}, {start}." },
    after: { text: "{egg}, {start}." },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'setup.egg', row: "shared with iOS",
    before: { text: "{mass} eggs" },
    after: { text: "{mass} eggs" },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'setup.from.fridge', row: "shared with iOS",
    before: { text: "from the fridge" },
    after: { text: "from the fridge" },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'setup.from.room', row: "shared with iOS",
    before: { text: "at room temperature" },
    after: { text: "at room temperature" },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'setup.from.custom', row: "shared with iOS",
    before: { text: "at {temp}" },
    after: { text: "at {temp}" },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'setup.start.cold', row: "shared with iOS",
    before: { text: "into cold water and boiled" },
    after: { text: "into cold water and boiled" },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'setup.start.coldStanding', row: "shared with iOS",
    before: { text: "into cold water, brought to the boil and left to stand" },
    after: { text: "into cold water, brought to the boil and left to stand" },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'setup.start.hot', row: "shared with iOS",
    before: { text: "into boiling water" },
    after: { text: "into boiling water" },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'setup.start.hotStanding', row: "shared with iOS",
    before: { text: "into boiling water and left to stand" },
    after: { text: "into boiling water and left to stand" },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'setup.start.sous', row: "shared with iOS",
    before: { text: "sous-vide at {bath}" },
    after: { text: "sous-vide at {bath}" },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'setup.cooling.ice', row: "shared with iOS",
    before: { text: "then an ice bath" },
    after: { text: "then an ice bath" },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'setup.cooling.tap', row: "shared with iOS",
    before: { text: "then under a cold tap" },
    after: { text: "then under a cold tap" },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'setup.cooling.counter', row: "shared with iOS",
    before: { text: "then onto the counter" },
    after: { text: "then onto the counter" },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'setup.clause', row: "shared with iOS",
    before: { text: "{label}: {value}, change" },
    after: { text: "{label}: {value}, change" },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'setup.close', row: "shared with iOS",
    before: { text: "Done" },
    after: { text: "Done" },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'idle.welcome', row: "shared with iOS",
    before: { text: "Our first egg together. I start off guessing from a generic egg, but as you give me feedback, I learn to specialise on you." },
    after: { text: "Our first egg together. I start off guessing from a generic egg, but as you give me feedback, I learn to specialise on you." },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'controls.probe', row: "retired on iOS",
    before: { text: "Ask for a probe reading" },
    after: null,
    appsBefore: ["ios"], appsAfter: [],
  },
  {
    key: 'controls.probe.hint', row: "retired on iOS",
    before: { text: "When the cooling ends, I'll ask for one reading from the middle of the egg. From a single egg, that tells me how fast your eggs heat." },
    after: null,
    appsBefore: ["ios"], appsAfter: [],
  },
  {
    key: 'controls.thermometer', row: "shared with iOS",
    before: { text: "Probe thermometer" },
    after: { text: "Probe thermometer" },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'controls.thermometer.more', row: "shared with iOS",
    before: { text: "If you have a probe thermometer, I'll ask for one reading when the cooling countdown ends. That's the moment the middle of the yolk is at its warmest, so push the tip to the very middle and tell me the highest number you see: anywhere else, or any later, reads lower. From that single egg I learn how fast heat gets into your eggs. I don't ask when the eggs rest on the counter, because nothing is counted down." },
    after: { text: "If you have a probe thermometer, I'll ask for one reading when the cooling countdown ends. That's the moment the middle of the yolk is at its warmest, so push the tip to the very middle and tell me the highest number you see: anywhere else, or any later, reads lower. From that single egg I learn how fast heat gets into your eggs. I don't ask when the eggs rest on the counter, because nothing is counted down." },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'pan.waterBoilsAt', row: "retired on iOS",
    before: { text: "Water boils at" },
    after: null,
    appsBefore: ["ios"], appsAfter: [],
  },
  {
    key: 'pan.timeToBoil', row: "retired on iOS",
    before: { text: "Time to boil" },
    after: null,
    appsBefore: ["ios"], appsAfter: [],
  },
  {
    key: 'pan.timeToBoil.assumed', row: "retired on iOS",
    before: { text: "{time} (assumed)" },
    after: null,
    appsBefore: ["ios"], appsAfter: [],
  },
  {
    key: 'pan.measured', row: "retired on iOS",
    before: { text: "Based on history with this much water. I update it each time you tap the boil on a cold-water start." },
    after: null,
    appsBefore: ["ios"], appsAfter: [],
  },
  {
    key: 'pan.unmeasured', row: "retired on iOS",
    before: { text: "Tap the boil on a cold-water start and I'll remember for next time." },
    after: null,
    appsBefore: ["ios"], appsAfter: [],
  },
  {
    key: 'odds.shown', row: "retired on iOS",
    before: { text: "Showing" },
    after: null,
    appsBefore: ["ios"], appsAfter: [],
  },
  {
    key: 'odds.hidden', row: "retired on iOS",
    before: { text: "Hidden" },
    after: null,
    appsBefore: ["ios"], appsAfter: [],
  },
  {
    key: 'learned.literature', row: "shared with iOS",
    before: { text: "I haven't learned anything yet. I learn how fast your stove boils water when you tap the boil, and your eggs when you tell me how one came out." },
    after: { text: "I haven't learned anything yet. I learn how fast your stove boils water when you tap the boil, and your eggs when you tell me how one came out." },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'learned.pan', row: "shared with iOS",
    before: { text: "{water} of water takes about {time} to boil, based on history" },
    after: { text: "{water} of water takes about {time} to boil, based on history" },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'learned.both', row: "shared with iOS",
    before: { text: "{tuned} · {pan}" },
    after: { text: "{tuned} · {pan}" },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'learned.forget.more', row: "shared with iOS",
    before: { text: "This forgets every egg you've told me about and every boil you've timed, and I go back to what's true of eggs in general. You don't need it to undo a wrong answer or two: they wash out after a few more eggs. It's for a new stove, a new kitchen, or a fresh start." },
    after: { text: "This forgets every egg you've told me about and every boil you've timed, and I go back to what's true of eggs in general. You don't need it to undo a wrong answer or two: they wash out after a few more eggs. It's for a new stove, a new kitchen, or a fresh start." },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'learned.forgetExplain', row: "retired on iOS",
    before: { text: "Clears what I've learned from your answers and your boil times. A few wrong answers wash out after a few more eggs anyway; this is for when you'd rather not wait." },
    after: null,
    appsBefore: ["ios"], appsAfter: [],
  },
  {
    key: 'controls.thermometer.ask', row: "shared with iOS",
    before: { text: "Ask for a reading after each egg" },
    after: { text: "Ask for a reading after each egg" },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'colophon.name', row: "shared with iOS",
    before: { text: "Actual Egg Timer." },
    after: { text: "Actual Egg Timer." },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'colophon.lede', row: "shared with iOS",
    before: { text: "Times computed from heat conduction and denaturation kinetics, not from a recipe." },
    after: { text: "Times computed from heat conduction and denaturation kinetics, not from a recipe." },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'colophon.link', row: "shared with iOS",
    before: { text: "Source, and the physics it rests on" },
    after: { text: "Source, and the physics it rests on" },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'colophon.tail', row: "shared with iOS",
    before: { text: "— including what I get wrong." },
    after: { text: "— including what I get wrong." },
    appsBefore: ["web"], appsAfter: ["web","ios"],
  },
  {
    key: 'colophon.ios', row: "retired on iOS",
    before: { text: "I work out times from the physics and chemistry of eggs. Both heating and cooling matter for cooking the middle." },
    after: null,
    appsBefore: ["ios"], appsAfter: [],
  },
  {
    key: 'more.expanded', row: "new on iOS",
    before: null,
    after: { text: "Expanded" },
    appsBefore: [], appsAfter: ["ios"],
  },
  {
    key: 'more.collapsed', row: "new on iOS",
    before: null,
    after: { text: "Collapsed" },
    appsBefore: [], appsAfter: ["ios"],
  },
  {
    key: 'controls.units.more.ios', row: "new on iOS",
    before: null,
    after: { text: "Metric or Imperial, for every number I show and every number you set. I start with what's usual where your phone says you are. Switching changes only how I write the numbers: the egg and the times stay exactly the same, and the eggs don't mind which." },
    appsBefore: [], appsAfter: ["ios"],
  },
];

export const iosA: Draft = {
  base: '91d5fff',
  rows: IOS_A_DRAFT,
  exampleOnly: {},
};
