/**
 * fixtures/scenarios.json: whole cooks, solved end to end.
 */

import { eggFromMass, eggFromMinorDiameter } from '../../src/core/geometry.js';
import { boilingPointAtAltitude } from '../../src/core/thermo.js';
import { CookSetup } from '../../src/core/protocol.js';
import { simulate, solveCookTime, donenessFromSlider, DEFAULT_PARAMS } from '../../src/core/solve.js';

import { setupOf } from './shared.js';

/** The reference egg of the validation and the scenarios: 43.5 mm across,
 *  about 62.3 g - not the app's 68 g EU Large. Built from its mass: the iOS
 *  core, which only weighs eggs, builds it the same way (D4). */
const REFERENCE_EGG = eggFromMass(eggFromMinorDiameter(0.0435).mass_kg);

interface Scenario {
  name: string;
  setup: CookSetup;
  level: number;
}

const SCENARIOS: Scenario[] = [
  { name: 'jammy, fridge, sea level, ice', setup: setupOf({}), level: 0.41 },
  { name: 'jammy, room temp', setup: setupOf({ eggStart_C: 21, ambient_C: 21 }), level: 0.41 },
  { name: 'jammy, 2000 m', setup: setupOf({ boiling_C: boilingPointAtAltitude(2000) }), level: 0.41 },
  { name: 'runny', setup: setupOf({}), level: 0.0 },
  { name: 'hard', setup: setupOf({}), level: 1.0 },
  { name: 'cold start, 8 min ramp', setup: setupOf({ startMode: 'cold', timeToBoil_s: 480 }), level: 0.41 },
  { name: 'cold start, 12 min ramp', setup: setupOf({ startMode: 'cold', timeToBoil_s: 720 }), level: 0.41 },
  { name: 'counter rested', setup: setupOf({ cooling: 'counter' }), level: 0.41 },
  { name: 'cold tap', setup: setupOf({ cooling: 'tap' }), level: 0.41 },
  { name: 'eight eggs in 0.75 L', setup: setupOf({ eggCount: 8, waterLitres: 0.75 }), level: 0.41 },
  { name: 'standing, 8 min boil', setup: setupOf({ startMode: 'cold', afterBoil: 'off', timeToBoil_s: 480 }), level: 0.41 },
  { name: 'standing, 10 min boil, hard', setup: setupOf({ startMode: 'cold', afterBoil: 'off', timeToBoil_s: 600 }), level: 1.0 },
  { name: 'standing, 4 min boil: a fast hob is not a small pan', setup: setupOf({ startMode: 'cold', afterBoil: 'off', timeToBoil_s: 240 }), level: 0.41 },
  { name: 'standing, 1 L, hard (out of reach)', setup: setupOf({ startMode: 'cold', afterBoil: 'off', timeToBoil_s: 240, waterLitres: 1 }), level: 1.0 },
  { name: 'standing, 4 L, 16 min boil, hard', setup: setupOf({ startMode: 'cold', afterBoil: 'off', timeToBoil_s: 960, waterLitres: 4 }), level: 1.0 },
  { name: 'standing, hot start, 1 L (white never sets)', setup: setupOf({ afterBoil: 'off', timeToBoil_s: 480, waterLitres: 1 }), level: 0.41 },
  { name: 'standing, hot start, 6 L, two eggs', setup: setupOf({ afterBoil: 'off', timeToBoil_s: 480, waterLitres: 6, eggCount: 2 }), level: 0.41 },
];

export const scenariosFixture = {
  $comment: 'Generated by tools/fixtures.ts. Whole cooks, solved end to end.',
  generator: 'npm run fixtures',
  egg: {
    mass_kg: REFERENCE_EGG.mass_kg,
    radius_m: REFERENCE_EGG.radius_m,
  },
  params: DEFAULT_PARAMS,
  cases: SCENARIOS.map((s) => {
    const sol = solveCookTime(REFERENCE_EGG, s.setup, DEFAULT_PARAMS, donenessFromSlider(s.level));
    const fixed = simulate(REFERENCE_EGG, s.setup, DEFAULT_PARAMS, 7.4 * 60);
    return {
      name: s.name,
      level: s.level,
      setup: s.setup,
      solution: {
        reachable: sol.reachable,
        whiteSets: sol.whiteSets,
        softestLevel: sol.softestLevel,
        hardestLevel: sol.hardestLevel,
        minCookTime_s: sol.minCookTime_s,
        cookTime_s: sol.result.cookTime_s,
        peakYolk_C: sol.result.peakYolk_C,
        peakWhite_C: sol.result.peakWhite_C,
        yolkAtPull_C: sol.result.yolkAtPull_C,
        yolkDose_min: sol.result.yolkDose_min,
        whiteDose_min: sol.result.whiteDose_min,
      },
      atFixed444s: {
        peakYolk_C: fixed.peakYolk_C,
        yolkDose_min: fixed.yolkDose_min,
        whiteDose_min: fixed.whiteDose_min,
      },
    };
  }),
};
