/**
 * Golden fixtures: the TypeScript core's answers, written out so another
 * implementation can be held to them.
 *
 * This is the contract for the Swift port (`ios/`). The rule is that the
 * fixtures are generated ONLY from this implementation, and the port never
 * regenerates them to make itself pass - if a number here is wrong, it is wrong
 * in `src/core/` first, and `npm test` should be what catches it.
 *
 * Run: npm run fixtures
 *
 * Two files, because they have different lifetimes:
 *
 *   fixtures/core.json      pure functions - the port covers these today
 *   fixtures/scenarios.json whole cooks - the port covers these when the
 *                           solver lands, and they are generated now so the
 *                           target exists before the code does
 */

import { writeFileSync, mkdirSync } from 'node:fs';

import {
  MODE_COUNT, ALPHA_DEFAULT, YOLK_RADIUS_FRAC, Z_YOLK, TREF_YOLK_C, Z_WHITE,
  TREF_WHITE_C, H_EFF, K_EGG, RAMP_R, TAU_STANDING_SCALE, TAU_AIR, T_ICE_BATH_C,
  T_COLD_TAP_C, T_ROOM_C, TAU_PLUNGE, TAU_DIP_RECOVERY, C_WATER, C_EGG, RHO_EGG,
  EGG_VOLUME_COEFF, EGG_LENGTH_RATIO, DT_SIM, CARRYOVER_WINDOW,
} from '../src/core/constants.js';
import {
  eggFromMass, eggFromMinorDiameter, diffusionTime, eggVolumeFromMinorDiameter,
} from '../src/core/geometry.js';
import {
  pressureAtAltitude, boilingPointAtPressure, boilingPointAtAltitude,
  boilingPointApprox, saltBoilingElevation,
} from '../src/core/thermo.js';
import {
  createDose, accumulateDose, holdTimeForDose, zFromActivationEnergy,
} from '../src/core/kinetics.js';
import {
  createSphere, stepSphere, temperatureAt, centreTemperature, meanTemperature,
  seriesTheta, erfcTheta, oneTermTheta, biotNumber, erfc,
} from '../src/core/sphere.js';
import { CookSetup } from '../src/core/protocol.js';
import {
  simulate, solveCookTime, donenessFromSlider, DEFAULT_PARAMS,
} from '../src/core/solve.js';

/* ------------------------------------------------------------------ cases */

/** Sample points chosen to sit where the model actually lives, plus the edges
 *  that break naive implementations: x = 0 (the sinc singularity), tiny Fo
 *  (slow convergence), large Fo (everything underflows). */
const THETA_CASES: Array<[number, number]> = [];
for (const x of [0.0, 0.1, 0.35, 0.693, 0.9, 1.0]) {
  for (const fo of [0.01, 0.0688, 0.07434, 0.15, 0.229, 0.5, 1.0]) {
    THETA_CASES.push([x, fo]);
  }
}

const ERFC_CASES = [-3.0, -1.0, -0.25, 0.0, 1e-9, 0.25, 0.5, 1.0, 2.0, 3.5, 6.0];
const MASS_CASES_G = [40, 48, 53, 58, 62.3, 68, 76, 90];
const MINOR_CASES_MM = [36, 40, 43.5, 44.8, 48, 52];
const ALTITUDE_CASES_M = [-400, 0, 500, 1000, 1609, 2000, 3000, 4000, 5000];
const PRESSURE_CASES_PA = [101325, 95000, 89870, 79500, 70110, 54020];

function round(value: number): number {
  // JSON.stringify already emits the shortest round-tripping form of a double,
  // so nothing is lost here. This only exists to keep the file readable.
  return value;
}

/* ------------------------------------------------------------- core.json */

const sphereStep = (() => {
  // A short, fully specified integration: the exact arithmetic the port has to
  // reproduce, including the mode coupling and the exponential decay.
  const s = createSphere(0.0238, ALPHA_DEFAULT, 4.0, 100.0);
  const samples: Array<Record<string, number>> = [];
  let t = 0;
  for (let i = 0; i < 40; i++) {
    stepSphere(s, 10.0, 100.0);
    t += 10;
    samples.push({
      t_s: t,
      centre_C: round(centreTemperature(s)),
      yolkBoundary_C: round(temperatureAt(s, YOLK_RADIUS_FRAC)),
      mean_C: round(meanTemperature(s)),
    });
  }
  return samples;
})();

const rampedStep = (() => {
  // The same integrator driven by a MOVING surface, which is the case the
  // Duhamel coupling exists for. A step-only test would not catch a sign error
  // in the drive term.
  const s = createSphere(0.0238, ALPHA_DEFAULT, 4.0, 20.0);
  const samples: Array<Record<string, number>> = [];
  for (let i = 1; i <= 30; i++) {
    const surface = 20.0 + i * 2.5;
    stepSphere(s, 15.0, surface);
    samples.push({
      t_s: i * 15,
      surface_C: surface,
      centre_C: round(centreTemperature(s)),
      mean_C: round(meanTemperature(s)),
    });
  }
  return samples;
})();

const core = {
  $comment: 'Generated by tools/fixtures.ts from src/core/. Do not hand-edit.',
  generator: 'npm run fixtures',
  constants: {
    MODE_COUNT, ALPHA_DEFAULT, YOLK_RADIUS_FRAC, Z_YOLK, TREF_YOLK_C, Z_WHITE,
    TREF_WHITE_C, H_EFF, K_EGG, RAMP_R, TAU_STANDING_SCALE, TAU_AIR,
    T_ICE_BATH_C, T_COLD_TAP_C, T_ROOM_C, TAU_PLUNGE, TAU_DIP_RECOVERY,
    C_WATER, C_EGG, RHO_EGG, EGG_VOLUME_COEFF, EGG_LENGTH_RATIO, DT_SIM,
    CARRYOVER_WINDOW,
  },
  sphere: {
    seriesTheta: THETA_CASES.map(([x, fo]) => ({ x: x, fourier: fo, value: round(seriesTheta(x, fo)) })),
    erfcTheta: THETA_CASES.map(([x, fo]) => ({ x: x, fourier: fo, value: round(erfcTheta(x, fo)) })),
    oneTermTheta: THETA_CASES.map(([x, fo]) => ({ x: x, fourier: fo, value: round(oneTermTheta(x, fo)) })),
    erfc: ERFC_CASES.map((x) => ({ x: x, value: round(erfc(x)) })),
    biotNumber: [500, 850, 1100].map((h) => ({ h_Wm2K: h, radius_m: 0.0238, value: round(biotNumber(h, 0.0238)) })),
    stepResponse: sphereStep,
    rampResponse: rampedStep,
  },
  geometry: {
    fromMass: MASS_CASES_G.map((g) => {
      const egg = eggFromMass(g / 1000);
      return {
        mass_g: g,
        radius_m: round(egg.radius_m),
        minorDiameter_m: round(egg.minorDiameter_m),
        volume_m3: round(egg.volume_m3),
        tau_s: round(diffusionTime(egg, ALPHA_DEFAULT)),
      };
    }),
    fromMinorDiameter: MINOR_CASES_MM.map((mm) => {
      const egg = eggFromMinorDiameter(mm / 1000);
      return {
        minorDiameter_mm: mm,
        radius_m: round(egg.radius_m),
        mass_kg: round(egg.mass_kg),
        volume_m3: round(egg.volume_m3),
        volumeDirect_m3: round(eggVolumeFromMinorDiameter(mm / 1000)),
      };
    }),
  },
  thermo: {
    pressureAtAltitude: ALTITUDE_CASES_M.map((h) => ({ altitude_m: h, value: round(pressureAtAltitude(h)) })),
    boilingPointAtAltitude: ALTITUDE_CASES_M.map((h) => ({ altitude_m: h, value: round(boilingPointAtAltitude(h)) })),
    boilingPointAtPressure: PRESSURE_CASES_PA.map((p) => ({ pressure_Pa: p, value: round(boilingPointAtPressure(p)) })),
    boilingPointApprox: ALTITUDE_CASES_M.map((h) => ({ altitude_m: h, value: round(boilingPointApprox(h)) })),
    saltBoilingElevation: [0, 6, 18, 36].map((g) => ({ gramsPerLitre: g, value: round(saltBoilingElevation(g)) })),
  },
  kinetics: {
    zFromActivationEnergy: [
      { ea_Jmol: 469e3, temperature_K: 338.15 },
      { ea_Jmol: 480e3, temperature_K: 353.15 },
      { ea_Jmol: 470e3, temperature_K: 338.0 },
    ].map((c) => ({ ...c, value: round(zFromActivationEnergy(c.ea_Jmol, c.temperature_K)) })),
    holdTimeForDose: [55, 60, 63, 65, 70, 80].map((held) => ({
      z_K: Z_YOLK, tref_C: TREF_YOLK_C, doseMinutes: 10.0, held_C: held,
      value: round(holdTimeForDose(createDose(Z_YOLK, TREF_YOLK_C), 10.0, held)),
    })),
    accumulateDose: (() => {
      // A ten-minute ramp from 50 to 80 C, integrated at the model's own step.
      const d = createDose(Z_YOLK, TREF_YOLK_C);
      const out: Array<Record<string, number>> = [];
      for (let i = 1; i <= 20; i++) {
        const temp = 50.0 + i * 1.5;
        accumulateDose(d, temp, 30.0);
        out.push({ step: i, temperature_C: temp, dt_s: 30.0, minutes: round(d.minutes) });
      }
      return out;
    })(),
  },
};

/* --------------------------------------------------------- scenarios.json */

const EU_LARGE = eggFromMinorDiameter(0.0435);

function setupOf(over: Partial<CookSetup>): CookSetup {
  const base: CookSetup = {
    startMode: 'hot',
    eggStart_C: 4,
    ambient_C: 20,
    boiling_C: 100,
    timeToBoil_s: 0,
    cooling: 'ice',
    waterLitres: 2,
    eggCount: 4,
    eggMass_kg: EU_LARGE.mass_kg,
  };
  return { ...base, ...over };
}

interface Scenario {
  name: string;
  setup: CookSetup;
  level: number;
}

const SCENARIOS: Scenario[] = [
  { name: 'jammy, fridge, sea level, ice', setup: setupOf({}), level: 0.41 },
  { name: 'jammy, room temp', setup: setupOf({ eggStart_C: 21, ambient_C: 21 }), level: 0.41 },
  { name: 'jammy, 2000 m', setup: setupOf({ boiling_C: boilingPointAtAltitude(2000) }), level: 0.41 },
  { name: 'runny', setup: setupOf({}), level: 0.0 },
  { name: 'hard', setup: setupOf({}), level: 1.0 },
  { name: 'cold start, 8 min ramp', setup: setupOf({ startMode: 'cold', timeToBoil_s: 480 }), level: 0.41 },
  { name: 'cold start, 12 min ramp', setup: setupOf({ startMode: 'cold', timeToBoil_s: 720 }), level: 0.41 },
  { name: 'counter rested', setup: setupOf({ cooling: 'counter' }), level: 0.41 },
  { name: 'cold tap', setup: setupOf({ cooling: 'tap' }), level: 0.41 },
  { name: 'eight eggs in 0.75 L', setup: setupOf({ eggCount: 8, waterLitres: 0.75 }), level: 0.41 },
  { name: 'standing, 8 min boil', setup: setupOf({ startMode: 'cold', afterBoil: 'off', timeToBoil_s: 480 }), level: 0.41 },
  { name: 'standing, 10 min boil, hard', setup: setupOf({ startMode: 'cold', afterBoil: 'off', timeToBoil_s: 600 }), level: 1.0 },
  { name: 'standing, 4 min boil (white never sets)', setup: setupOf({ startMode: 'cold', afterBoil: 'off', timeToBoil_s: 240 }), level: 0.41 },
];

const scenarios = {
  $comment: 'Generated by tools/fixtures.ts. The port covers these once solve.ts is ported.',
  generator: 'npm run fixtures',
  egg: {
    minorDiameter_m: EU_LARGE.minorDiameter_m,
    radius_m: EU_LARGE.radius_m,
    mass_kg: EU_LARGE.mass_kg,
  },
  params: DEFAULT_PARAMS,
  cases: SCENARIOS.map((s) => {
    const sol = solveCookTime(EU_LARGE, s.setup, DEFAULT_PARAMS, donenessFromSlider(s.level));
    const fixed = simulate(EU_LARGE, s.setup, DEFAULT_PARAMS, 7.4 * 60);
    return {
      name: s.name,
      level: s.level,
      setup: s.setup,
      solution: {
        reachable: sol.reachable,
        whiteSets: sol.whiteSets,
        softestLevel: round(sol.softestLevel),
        hardestLevel: round(sol.hardestLevel),
        minCookTime_s: round(sol.minCookTime_s),
        cookTime_s: round(sol.result.cookTime_s),
        peakYolk_C: round(sol.result.peakYolk_C),
        peakWhite_C: round(sol.result.peakWhite_C),
        yolkAtPull_C: round(sol.result.yolkAtPull_C),
        yolkDose_min: round(sol.result.yolkDose_min),
        whiteDose_min: round(sol.result.whiteDose_min),
      },
      atFixed444s: {
        peakYolk_C: round(fixed.peakYolk_C),
        yolkDose_min: round(fixed.yolkDose_min),
        whiteDose_min: round(fixed.whiteDose_min),
      },
    };
  }),
};

/* ------------------------------------------------------------------ write */

mkdirSync('fixtures', { recursive: true });
writeFileSync('fixtures/core.json', `${JSON.stringify(core, null, 2)}\n`);
writeFileSync('fixtures/scenarios.json', `${JSON.stringify(scenarios, null, 2)}\n`);

const counts = [
  `${core.sphere.seriesTheta.length} seriesTheta`,
  `${core.sphere.stepResponse.length} step samples`,
  `${core.sphere.rampResponse.length} ramp samples`,
  `${core.geometry.fromMass.length + core.geometry.fromMinorDiameter.length} geometry`,
  `${core.thermo.boilingPointAtAltitude.length} altitudes`,
  `${scenarios.cases.length} scenarios`,
];
console.log(`fixtures/core.json + fixtures/scenarios.json written: ${counts.join(', ')}`);
